import type { Metadata } from "next";
import { authClient } from "@/lib/auth/client";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth-ui";
import { Philosopher, Mulish } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const headerFont = Philosopher({
  weight: "700",
  variable: "--font-header",
  subsets: ["latin"],
});

const bodyFont = Mulish({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} ${headerFont.variable} h-full antialiased`}
      suppressHydrationWarning
      // need to suppress warning due to the way neonauthuiprovider works
    >
      <body className="min-h-full flex flex-col">
        <NeonAuthUIProvider authClient={authClient} emailOTP social={{ providers: ["google"] }} className="bg-white">
          <header className="flex h-16 items-center justify-between border-b p-4">
            <h1 className="text-xl font-bold">starter neon auth provider</h1>
            <nav>
              <Link href="/items">Inventory Items</Link>
            </nav>
            <UserButton size={"icon"} />
          </header>
          {children}
        </NeonAuthUIProvider>
      </body>
    </html>
  );
}
